### ISSUE TITLE
aws-exports issue?

### ISSUE THREAD

**Issue by idkjs** [dabit3/conference-app-in-a-box#2]
Greeting, @dabit3. Thanks for doing this work!

I just ran the project per the instructions and it runs but is throwing an error: `No credentials, applicationId or region`

`aws-exports.js` is generated but doesn't have those fields in it.

screenshot:

![Simulator Screen Shot - iPhone X - 2019-07-21 at 10 03 23](https://user-images.githubusercontent.com/2370391/61588719-8bcb8a00-aba0-11e9-978d-51a5bb4ac745.png)

So the app doesnt know where to look for the updates, i guess. 

console mutation returns:

```
{
  "data": {
    "createTalk": {
      "id": "77cbe3c5-563d-43f5-ab7b-2aa7e70b451d",
      "name": "Performance In React Native",
      "speakerBio": "Software Engineer at Facebook",
      "speakerName": "Ram Narasimhan",
      "speakerAvatar": "https://pbs.twimg.com/profile_images/875450414161772544/UjefWmmL_400x400.jpg",
      "location": "Armory",
      "date": "November 11",
      "time": "9:00 AM - 9:30 AM",
      "timeStamp": "1573491600"
    }
  }
}
```

![Simulator Screen Shot - iPhone X - 2019-07-21 at 10 18 10](https://user-images.githubusercontent.com/2370391/61589101-be2bb600-aba5-11e9-9323-d7428be586eb.png)

I am still working through this...if you already see whats going on, feel free to chime in, sir! Thank you.

**Comment by dabit3** [comment]
Hey @idkj, I think the issue here is something to do with Amazon Pinpoint, and It is a warning fortunately and not an error so it can be dismissed. This is something our team is aware of and we're trying to mitigate though.

On the other hand the query should still work! When you generated the resources by running `amplify push`, did the CLI generate new GraphQL queries for you? If so, you may need to update the `listTalks1 query to make sure that it looks like the one in [this file](https://github.com/dabit3/conference-app-in-a-box/blob/master/src/graphql/queries.js).

**Comment by idkjs** [comment]
Ok to error. I did have the cli generate the queries and ran `amplify push`. I just cp'd you file into queries to test it and still returns nothing. So I am understanding, i SHOULD NOT have had the cli generate the queries. Is that right?

At any rate, copying your `src/graphql` folder into my local version, did not fix the problem.

**Comment by dabit3** [comment]
Can you check the console for any errors and also log out the returned data from the GraphQL Query for `listTalks`?

**Comment by dabit3** [comment]
Hey, I'm testing this out now but I think the issue is that when prompted for `We already have the GraphQL code generated for this project, so generating it here is not necessary.`, you should choose __N__ since the graphql code is already part of the project. If you chose yes, you should be able to just copy over the code in the repo from the graphql folder directly into your project to overwrite the auto generated code.

There are just a couple of small differences, mostly around the listTalks query I think, that need to be adjusted for this app to work as intended. Either way, I'm testing this out now & will report back in just a sec.

**Comment by dabit3** [comment]
@idkjs I just tested this and it works as expected. I've updated the README to reflect the changes (don't automatically generate the queries). If you don't see the data in the app, make sure you're looking at the right day in the toggle (November 11) for the query / mutation.

**Comment by idkjs** [comment]
Got it working, boss, from previous comment but yeah, in case anyone add extra steps like i did, good idea to note it in the readme for us clowns. Peace to you, brother. Thank you for the feedback.
